apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  serviceName: postgres
  minReadySeconds: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - silverstone
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:14.2-bullseye
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-secret
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
          securityContext:
            runAsUser: 65534
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pvc
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: postgres-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        volumeName: postgres-pv
        resources:
          requests:
            storage: 50Gi
